server:
  port: 9000

logging:
  level:
    org.springframework: warn
  pattern:
    level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"

management:
  endpoints:
    web:
      exposure:
        include: health, info, refresh, busrefresh, metrics, prometheus  # Don't expose 'env' or 'configprops'
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
  info:
    env:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}

otel:
  service:
    name: ${spring.application.name}

spring:
  application:
    name: cards
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: 5672
    username: ${SPRING_RABBITMQ_USER:guest}
    password: ${SPRING_RABBITMQ_PASSWORD:guest}
  cloud:
    config:
      uri: http://${CONFIG_SERVER_HOST:localhost}:8071
      username: ${CONFIG_SERVER_USER}
      password: ${CONFIG_SERVER_PASSWORD}
  config:
    import: "configserver:${spring.cloud.config.uri}"

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${EUREKA_SERVER_HOST:localhost}:8070/eureka/

info:
  app:
    name: cards
    description: Eazybank Cards microservice
    version: 1.0.0
