server:
  port: 8072

logging:
  level:
    org.springframework: warn
    com.goutos.gateway: debug

resilience4j.circuitbreaker:
  configs:
    default:
      slidingWindowSize: 10 # that many requests will be considered for calculating the failure rate
      permittedNumberOfCallsInHalfOpenState: 2 # that many requests will be allowed in half-open state
      failureRateThreshold: 50 # % of requests must fail for the circuit breaker to trip
      waitDurationInOpenState: 10000 # how long the circuit breaker should stay in the open state before transitioning to half-open

management:
  endpoints:
    web:
      exposure:
        include: health, info, refresh, busrefresh, gateway, circuitbreakers, circuitbreakereventst, streamcircuitbreakereventst, shutdown  # Don't expose 'env' or 'configprops'
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
    shutdown:
      access: unrestricted
    gateway:
      access: unrestricted
  info:
    env:
      enabled: true

spring:
  application:
    name: gatewayserver
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: false # Disable default discovery locator and use only RouteLocator
              lowerCaseServiceId: true

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${EUREKA_SERVER_HOST:localhost}:8070/eureka/

info:
  app:
    name: gatewayserver
    description: Eazybank Api Gateway server
    version: 1.0.0


