server:
  port: 8072

logging:
  level:
    org.springframework: warn
    com.goutos.gateway: debug
  pattern:
    level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"

management:
  endpoints:
    web:
      exposure:
        include: health, info, refresh, busrefresh, shutdown, metrics, prometheus, gateway, circuitbreakers, circuitbreakereventst, streamcircuitbreakereventst  # Don't expose 'env' or 'configprops'
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
    shutdown:
      access: unrestricted
    gateway:
      access: unrestricted
  info:
    env:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}

otel:
  service:
    name: ${spring.application.name}

spring:
  application:
    name: gatewayserver
  data:
    redis:
      connect-timeout: 2s
      host: ${REDIS_HOST:localhost}
      port: 6379
      timeout: 1s
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: "http://${KEYCLOAK_HOST:localhost}:${KEYCLOAK_PORT:7080}/realms/master/protocol/openid-connect/certs"
  cloud:
    kubernetes:
      discovery:
        all-namespaces: true
        discovery-server-url: ${SPRING.CLOUD.KUBERNETES.DISCOVERY.DISCOVERY-SERVER-URL:http://spring-cloud-kubernetes-discoveryserver:80/}
    gateway:
      server:
        webflux:
          httpclient:
            connect-timeout: 1000
            response-timeout: 2s


resilience4j.circuitbreaker:
  configs:
    default:
      slidingWindowSize: 10 # that many requests will be considered for calculating the failure rate
      permittedNumberOfCallsInHalfOpenState: 2 # that many requests will be allowed in half-open state
      failureRateThreshold: 50 # % of requests must fail for the circuit breaker to trip
      waitDurationInOpenState: 10000 # how long the circuit breaker should stay in the open state before transitioning to half-open

resilience4j.timelimiter:
  configs:
    default:
      timeoutDuration: 4s # how long the circuit breaker/ time limiter should wait for a response

resilience4j.retry:
  configs:
    default:
      maxAttempts: 3
      waitDuration: 500
      enableExponentialBackoff: true
      exponentialBackoffMultiplier: 2
      ignoreExceptions:
        - java.lang.NullPointerException
      retryExceptions:
        - java.util.concurrent.TimeoutException

info:
  app:
    name: gatewayserver
    description: Eazybank Api Gateway server
    version: 1.0.0


