{{- define "common.serviceaccount" -}}
{{- if .Values.istio_enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.appLabel }}-sa
  namespace: {{ .Values.global.namespace | default "microservices" }}
  labels:
    app.kubernetes.io/name: {{ .Values.appLabel }}
    app.kubernetes.io/part-of: eazybank
  {{- if .Values.istio.serviceAccount.annotations }}
  annotations:
    {{- range $key, $value := .Values.istio.serviceAccount.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  {{- end }}
automountServiceAccountToken: true
{{- end }}
{{- end -}}
