apiVersion: v1
data:
  prometheus.yml: "global:\n  scrape_interval:     5s # Set the scrape interval to every 5 seconds.\n  evaluation_interval: 5s # Evaluate rules every 5 seconds.\n\nscrape_configs:\n  - job_name: 'accounts'\n    metrics_path: '/actuator/prometheus'\n    static_configs:\n      - targets: [ 'accounts:8080' ]\n  - job_name: 'loans'\n    metrics_path: '/actuator/prometheus'\n    static_configs:\n      - targets: [ 'loans:8090' ]\n  - job_name: 'cards'\n    metrics_path: '/actuator/prometheus'\n    static_configs:\n      - targets: [ 'cards:9000' ]\n  - job_name: 'gatewayserver'\n    metrics_path: '/actuator/prometheus'\n    static_configs:\n      - targets: [ 'gatewayserver:8072' ]\n  - job_name: 'eurekaserver'\n    metrics_path: '/actuator/prometheus'\n    static_configs:\n      - targets: [ 'eurekaserver:8070' ]\n  - job_name: 'configserver'\n    metrics_path: '/actuator/prometheus'\n    static_configs:\n      - targets: [ 'configserver:8071' ]\n  \n"
kind: ConfigMap
metadata:
  annotations:
    use-subpath: "true"
  labels:
    io.kompose.service: prometheus
  name: prometheus-cm0
