server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health, info, refresh, busrefresh

spring:
  application:
    name: accounts
  datasource:
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
  jpa:
#    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  rabbitmq:
    host: localhost
    port: 5672
    username: ${RABBITMQ_USER:guest}
    password: ${RABBITMQ_PASSWORD:guest}
  cloud:
    config:
      uri: ${SPRING_CLOUD_CONFIG_URI:http://localhost:8071}
      username: ${CONFIG_SERVER_USER}
      password: ${CONFIG_SERVER_PASSWORD}
  config:
    import: "configserver:${spring.cloud.config.uri}"

