server:
  port: 8080

spring:
  application:
    name: accounts
  datasource:
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
  jpa:
#    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  cloud:
    config:
      uri: http://localhost:8071/
      username: ${CONFIG_SERVER_USER}
      password: ${CONFIG_SERVER_PASSWORD}
  config:
    import: "optional:configserver:http://localhost:8071/"
