server:
  port: 9010

logging:
  level:
    org.springframework: warn
    org.apache.kafka: error

spring:
  application:
    name: message
  cloud:
    function:
      definition: email|sms # This line defines the function composition. It means that the output of the 'email' function will be sent to the input of the 'sms' function. You can change this to 'email' or 'sms' if you want to use them separately.
    stream:
      default-binder: ${SPRING_CLOUD_STREAM_DEFAULT_BINDER:kafka} # This line specifies the default binder to use. You can change it to 'rabbit' if you want to use RabbitMQ.
      bindings:
        emailsms-in-0:
          destination: send-communication
          group: ${spring.application.name}
        emailsms-out-0:
          destination: communication-sent
      kafka:
        binder:
          brokers:
            - ${KAFKA_HOST:localhost}:9092
      binders:
        rabbit:
          type: rabbit
          environment:
             spring:
               rabbitmq:
                 host: ${RABBITMQ_HOST:localhost}
                 port: 5672
                 username: ${SPRING_RABBITMQ_USER:guest}
                 password: ${SPRING_RABBITMQ_PASSWORD:guest}
        kafka:
          type: kafka
          environment:
            spring:
              kafka:
                bootstrap-servers: ${KAFKA_HOST:localhost}:9092
                consumer:
                  auto-offset-reset: earliest
                producer:
                  acks: all
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: 5672
    username: ${SPRING_RABBITMQ_USER:guest}
    password: ${SPRING_RABBITMQ_PASSWORD:guest}
