user  nginx;
worker_processes  5;

events {
  worker_connections   1000;
}

http {
  upstream read_upstream {
    server read:3100;
  }

  upstream write_upstream {
    server write:3100;
  }

  server {
    listen 3100;

    location = / {
      return 200 'OK';
      auth_basic off;
    }

    location = /api/prom/push {
      proxy_pass http://write_upstream;
    }

    location = /api/prom/tail {
      proxy_pass http://read_upstream;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection "upgrade";
    }

    location ~ /api/prom/.* {
      proxy_pass http://read_upstream;
    }

    location = /loki/api/v1/push {
      proxy_pass http://write_upstream;
    }

    location = /loki/api/v1/tail {
      proxy_pass http://read_upstream;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection "upgrade";
    }

    location ~ /loki/api/.* {
      proxy_pass http://read_upstream;
    }
  }
}