services:
  network-deploy-service:
    networks:
      - microservices-network

  microservice-base-config:
    extends:
      service: network-deploy-service
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
    environment:
      SPRING_RABBITMQ_HOST: "rabbit"
      SPRING_PROFILES_ACTIVE: default
      SPRING_CLOUD_CONFIG_URI: http://configserver:8071