services:
  rabbit:
    image: rabbitmq:4.2.5-management-alpine
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s
    extends:
      file: common-config.yml
      service: network-deploy-service

  accountsdb:
    image: mysql:lts
    container_name: accountsdb
    ports:
      - "3307:3306"
    volumes:
      - accounts-data:/var/lib/mysql
    env_file:
      - .env
      - .env.${APP_ENV}
    environment:
      MYSQL_DATABASE: accountsdb
    extends:
      file: common-config.yml
      service: microservice-db-config

  loansdb:
    image: mysql:lts
    container_name: loansdb
    ports:
      - "3308:3306"
    volumes:
      - loans-data:/var/lib/mysql
    env_file:
      - .env
      - .env.${APP_ENV}
    environment:
      MYSQL_DATABASE: loansdb
    extends:
      file: common-config.yml
      service: microservice-db-config

  cardsdb:
    image: mysql:lts
    container_name: cardsdb
    ports:
      - "3309:3306"
    volumes:
      - cards-data:/var/lib/mysql
    env_file:
      - .env
      - .env.${APP_ENV}
    environment:
      MYSQL_DATABASE: cardsdb
    extends:
      file: common-config.yml
      service: microservice-db-config

  eurekaserver:
    image: ggoutos/eurekaserver:${IMAGE_TAG}
    container_name: eurekaserver-ms
    ports:
      - "8070:8070"
    healthcheck:
      test: [ "CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:8070/actuator/health/readiness || exit 1" ]
    env_file:
      - .env
      - .env.${APP_ENV}
    extends:
      file: common-config.yml
      service: microservice-base-config

  gatewayserver:
    image: ggoutos/gatewayserver:${IMAGE_TAG}
    container_name: gatewayserver-ms
    ports:
      - "8072:8072"
    healthcheck:
      test: [ "CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:8072/actuator/health/readiness || exit 1" ]
    depends_on:
      eurekaserver:
        condition: service_healthy
    env_file:
      - .env
      - .env.${APP_ENV}
    extends:
      file: common-config.yml
      service: microservice-base-config

  configserver:
    image: ggoutos/configserver:${IMAGE_TAG}
    container_name: configserver-ms
    ports:
      - "8071:8071"
    healthcheck:
      test: [ "CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:8071/actuator/health/readiness || exit 1" ]
    depends_on:
      rabbit:
        condition: service_healthy
    env_file:
      - .env
      - .env.${APP_ENV}
    extends:
      file: common-config.yml
      service: microservice-base-config

  accounts:
    image: ggoutos/accounts:${IMAGE_TAG}
    container_name: accounts-ms
    ports:
      - "8080:8080"
    healthcheck:
      test: [ "CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:8080/actuator/health/readiness || exit 1" ]
    depends_on:
      eurekaserver:
        condition: service_healthy
      accountsdb:
        condition: service_healthy
      configserver:
        condition: service_healthy
    env_file:
      - .env
      - .env.${APP_ENV}
    extends:
      file: common-config.yml
      service: microservice-base-config

  cards:
    image: ggoutos/cards:${IMAGE_TAG}
    container_name: cards-ms
    ports:
      - "9000:9000"
    healthcheck:
      test: [ "CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:9000/actuator/health/readiness || exit 1" ]
    depends_on:
      eurekaserver:
        condition: service_healthy
      cardsdb:
        condition: service_healthy
      configserver:
        condition: service_healthy
    env_file:
      - .env
      - .env.${APP_ENV}
    extends:
      file: common-config.yml
      service: microservice-base-config

  loans:
    image: ggoutos/loans:${IMAGE_TAG}
    container_name: loans-ms
    ports:
      - "8090:8090"
    healthcheck:
      test: [ "CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:8090/actuator/health/readiness || exit 1" ]
    depends_on:
      eurekaserver:
        condition: service_healthy
      loansdb:
        condition: service_healthy
      configserver:
        condition: service_healthy
    environment:
      - BPL_JVM_THREAD_COUNT=50 # Tells Paketo Buildpacks memory calculator the expected thread count
      - JAVA_TOOL_OPTIONS=-XX:ActiveProcessorCount=1 -Xss256k   # XX:ActiveProcessorCount Aligns JVM CPU detection with the container's CPU limit
                                                                # Xss256k Reduces per-thread stack size from default 1MB to 256KB
    env_file:
      - .env
      - .env.${APP_ENV}
    extends:
      file: common-config.yml
      service: microservice-base-config

networks:
  microservices-network:
    driver: bridge

volumes:
  accounts-data:
  cards-data:
  loans-data: