services:
  rabbit:
    image: rabbitmq:4.2.5-management-alpine
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s
    extends:
      file: common-config.yml
      service: network-deploy-service

  accountsdb:
    image: mysql:lts
    container_name: accountsdb
    ports:
      - "3307:3306"
    env_file:
      - .env
      - .env.${APP_ENV}
    environment:
      MYSQL_DATABASE: accountsdb
    extends:
      file: common-config.yml
      service: microservice-db-config

  loansdb:
    image: mysql:lts
    container_name: loansdb
    ports:
      - "3308:3306"
    env_file:
      - .env
      - .env.${APP_ENV}
    environment:
      MYSQL_DATABASE: loansdb
    extends:
      file: common-config.yml
      service: microservice-db-config

  cardsdb:
    image: mysql:lts
    container_name: cardsdb
    ports:
      - "3309:3306"
    env_file:
      - .env
      - .env.${APP_ENV}
    environment:
      MYSQL_DATABASE: cardsdb
    extends:
      file: common-config.yml
      service: microservice-db-config

  configserver:
    image: ${CONFIGSERVER_IMAGE}
    container_name: configserver-ms
    ports:
      - "8071:8071"
    depends_on:
      rabbit:
        condition: service_healthy
    env_file:
      - .env
      - .env.${APP_ENV}
    extends:
      file: common-config.yml
      service: microservice-base-config

  accounts:
    image: ${ACCOUNTS_IMAGE}
    container_name: accounts-ms
    ports:
      - "8080:8080"
    depends_on:
      accountsdb:
        condition: service_healthy
      configserver:
        condition: service_healthy
    env_file:
      - .env
      - .env.${APP_ENV}
    extends:
      file: common-config.yml
      service: microservice-base-config

  cards:
    image: ${CARDS_IMAGE}
    container_name: cards-ms
    ports:
      - "9000:9000"
    depends_on:
      cardsdb:
        condition: service_healthy
      configserver:
        condition: service_healthy
    env_file:
      - .env
      - .env.${APP_ENV}
    extends:
      file: common-config.yml
      service: microservice-base-config

  loans:
    image: ${LOANS_IMAGE}
    container_name: loans-ms
    ports:
      - "8090:8090"
    depends_on:
      loansdb:
        condition: service_healthy
      configserver:
        condition: service_healthy
    environment:
      - BPL_JVM_THREAD_COUNT=50 # Tells Paketo Buildpacks memory calculator the expected thread count
      - JAVA_TOOL_OPTIONS=-XX:ActiveProcessorCount=1 -Xss256k   # XX:ActiveProcessorCount Aligns JVM CPU detection with the container's CPU limit
                                                                # Xss256k Reduces per-thread stack size from default 1MB to 256KB
    env_file:
      - .env
      - .env.${APP_ENV}
    extends:
      file: common-config.yml
      service: microservice-base-config

networks:
  microservices-network:
    driver: bridge